DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE PACIENTE CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE CITA CASCADE CONSTRAINTS;
DROP TABLE DIAGNOSTICO CASCADE CONSTRAINTS;
DROP TABLE MEDICO_PACIENTE CASCADE CONSTRAINTS;

CREATE TABLE USUARIO(
id          NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOT NULL, 
nombre      VARCHAR2(50) NOT NULL, 
apellidos   VARCHAR2(50) NOT NULL, 
usuario     VARCHAR2(50) NOT NULL,
clave       VARCHAR2(50) NOT NULL, 
CONSTRAINT usr_pk PRIMARY KEY(id),
CONSTRAINT usr_ak UNIQUE(usuario)
);

CREATE TABLE MEDICO(
id              NUMBER(19,0) NOT NULL,
num_colegiado   VARCHAR2(50) NOT NULL,
CONSTRAINT med_pk PRIMARY KEY(id),
CONSTRAINT med_ak UNIQUE(num_colegiado),
CONSTRAINT med_fk_usr
    FOREIGN KEY (id) REFERENCES USUARIO(id)
);

CREATE TABLE PACIENTE(
id          NUMBER(19,0)    NOT NULL,
nss         VARCHAR2(50)    NOT NULL, 
num_tarjeta VARCHAR2(50)    NOT NULL,
telefono    VARCHAR2(50)    NOT NULL, 
direccion   VARCHAR2(100)   NOT NULL, 
CONSTRAINT pac_pk PRIMARY KEY(id),
CONSTRAINT pac_ak UNIQUE(nss),
CONSTRAINT pac_fk_usr
    FOREIGN KEY (id) REFERENCES USUARIO(id)
);

CREATE TABLE MEDICO_PACIENTE(
fk_medico   NUMBER(19,0) NOT NULL,
fk_paciente NUMBER(19,0) NOT NULL,
CONSTRAINT med_pac_pk PRIMARY KEY (fk_medico, fk_paciente),
CONSTRAINT med_pac_fk_medico FOREIGN KEY(fk_medico)
    REFERENCES MEDICO(id),
CONSTRAINT med_pac_fk_paciente FOREIGN KEY(fk_paciente)
    REFERENCES PACIENTE(id)
);

CREATE TABLE CITA(
id              NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOT NULL, 
fecha_hora      TIMESTAMP (6)   NOT NULL, 
motivo_cita     VARCHAR2(255)   NOT NULL,
fk_medico       NUMBER(19,0)    NOT NULL, 
fk_paciente     NUMBER(19,0)    NOT NULL, 
CONSTRAINT cita_pk PRIMARY KEY (id),
CONSTRAINT cita_fk_medico FOREIGN KEY(fk_medico)
    REFERENCES MEDICO(id),
CONSTRAINT cita_fk_paciente FOREIGN KEY(fk_paciente)
    REFERENCES PACIENTE(id)
);

CREATE TABLE DIAGNOSTICO(
id                          NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOT NULL, 
valoracion_especialista     VARCHAR2(255)   NOT NULL,
enfermedad                  VARCHAR2(255)   NOT NULL,
fk_cita                     NUMBER(19,0),
CONSTRAINT diag_pk PRIMARY KEY (id),
CONSTRAINT diag_ak UNIQUE(fk_cita),
CONSTRAINT diag_fk_cita FOREIGN KEY(fk_cita)
    REFERENCES CITA(id)
);
